### PR TITLE
fix: improve initial distribution of toolbar elements

### LINKED ISSUE #72: Never slot more than `maxToolbarItems` in toolbar
We currently slot all items in the toolbar and wait for a render to decide if they fit or needs to be moved to the menu.
However, after the introduction of `maxToolbarItems`, there could be a set limit on how many items should appear on the toolbar and there's no point waiting for renders as long as we're above that limit.
The current behavior, especially with a lot of items, creates a visually slow and unpleasant effect where the items are "sucked into" the menu on first render(s).

### PR DESCRIPTION
**Pull request by megheaiulian**
Fixes #72 

Initially distributes only maxToolbarItems to toolbar slot and the rest of the action go to the menu slot.
debouncer afterwards adjusts this depending on the size of elements

### CODE REVIEW

File: cosmoz-bottom-bar.js [hunk 1]
```diff
@@ -417,15 +417,6 @@ class CosmozBottomBar extends mixinBehaviors([IronResizableBehavior], PolymerEle
 			this._hideTimeout = setTimeout(onEnd, 510);
 		});
 	}
-
-	_toolbarMoveToStart(node) {
```
Comment (megheaiulian) [inline cosmoz-bottom-bar.js:421]: this was unused
